# PHP CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers

    steps:
      # Prepare for later installations
      - run:
          name: "Update apt"
          command: sudo apt-get update

      - run:
          name: "Install svn for WordPress"
          command: sudo apt-get install subversion

      - run:
          name: "Install MySQL"
          command: |
            sudo apt-get update && sudo apt-get install mysql-server
            sudo service mysql status || sudo service mysql start
            sudo docker-php-ext-install mysqli

      # Install phpcs
      - run:
          name: "Install phpcs"
          command: |
            mkdir ~/php-codesniffer && curl -L https://github.com/squizlabs/PHP_CodeSniffer/archive/master.tar.gz | tar xz --strip-components=1 -C ~/php-codesniffer

      # Install phpunit
      - run:
          name: "Install PHPUnit"
          command: |
            sudo wget -O /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-6.phar
            sudo chmod +x /usr/local/bin/phpunit

      # Check out the code.
      - checkout

      - run:
          name: "Prepare test database"
          command: |
            sudo mysql -uroot mysql -e "UPDATE user SET plugin='mysql_native_password' WHERE User='root'; FLUSH PRIVILEGES"
            bash .bin/install-wp-tests.sh "wp_tests" "root" "" "127.0.0.1"

      - run:
          name: "Run PHPUnit"
          command: |
            mkdir -p ~/phpunit
            phpunit --log-junit ~/phpunit/junit.xml

      # Teardown
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit
