# PHP CircleCI 2.0 configuration file

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.0-apache-node-browsers
        environment:
          plugin_slug: post-cloner
          plugin_dir: /wordpress/wp-content/plugins/$plugin_slug
          plugin_tests_dir: /home/ubuntu/wordpress-develop/src/wp-content/plugins/$plugin_slug/tests

      - image: circleci/mysql:5.7

    steps:
      - checkout
      # No password is required for the MySQL user `ubuntu`
      - run: mysql -u ubuntu -e "CREATE DATABASE wordpress"

      # Use cURL to fetch WP-CLI
      - run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

      # Make sure WP-CLI is executable
      - run: chmod +x wp-cli.phar

      # Download WordPress into `wordpress` directory
      - run: ./wp-cli.phar core download --allow-root --path=wordpress

      # move plugin into tests/src
      - run: mv $plugin_loc $plugin_dir;

      # And use WP-CLI to activate it
      - run: ./wp-cli.phar plugin activate $plugin_slug --path=wordpress

      # setup phpunit
      - run: wget https://phar.phpunit.de/phpunit.phar && chmod +x phpunit.phar && mv phpunit.phar /home/ubuntu/.phpenv/shims/phpunit

      # This is just for us to see that the WP Pusher plugin was actually installed and is active
      - run: ./wp-cli.phar plugin list --path=wordpress

      # comment out the below line to run a code coverage report.
      - run: cd $plugin_tests_dir; cd ..; pwd; ls; phpunit