# PHP CircleCI 2.0 configuration file

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.0-apache-node-browsers
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=ubuntu
          - MYSQL_DB=wordpress

    steps:
      - checkout

      # Use cURL to fetch WP-CLI
      - run:
        name: Fetch WP CLIS
        command: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

      # Make sure WP-CLI is executable
      - run:
        name: Ensure WP CLI is executable
        command: chmod +x wp-cli.phar

      # Download WordPress into `wordpress` directory
      - run:
        name: Download WordPress
        command: ./wp-cli.phar core download --allow-root --path=wordpress

      # Setup phpunit
      - run:
        name: Setup PHPunit
        command: wget https://phar.phpunit.de/phpunit.phar && chmod +x phpunit.phar && mv phpunit.phar /home/ubuntu/.phpenv/shims/phpunit

      # Move plugin into plugins dir
      - run:
        name: Move plugin into the appropriate folder
        command: mv /post-cloner /wordpress/wp-content/plugins/post-cloner;

      # And use WP-CLI to activate it
      - run:
        name: Activate plugin with WP CLI
        command: ./wp-cli.phar plugin activate post-cloner --path=wordpress

      # This is just for us to see that our plugin was actually installed and is active
      - run:
        name: Check active plugins
        command: ./wp-cli.phar plugin list --path=wordpress

      # Test the sucker
      - run:
        name: Run tests
        command: cd /wordpress/wp-content/plugins/post-cloner/tests; cd ..; pwd; ls; phpunit